version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-auth
    environment:
      POSTGRES_DB: assurePlusBD
      POSTGRES_USER: kse
      POSTGRES_PASSWORD: "@Kse12345"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - assureplus-net

  redis:
    image: redis:7-alpine
    container_name: redis-auth
    ports:
      - "6379:6379"
    networks:
      - assureplus-net

  auth-service:
    build: .
    container_name: auth-service
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/assurePlusBD
      SPRING_DATASOURCE_USERNAME: kse
      SPRING_DATASOURCE_PASSWORD: "@Kse12345"
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: prod
      # --- Exemple pour base distante ---
      # SPRING_DATASOURCE_URL: jdbc:postgresql://192.168.1.102:5432/assurePlusBD
      # SPRING_DATASOURCE_USERNAME: kse
      # SPRING_DATASOURCE_PASSWORD: "@Kse12345"
    ports:
      - "8080:8080"
    networks:
      - assureplus-net

volumes:
  pgdata:

networks:
  assureplus-net:
    driver: bridge 