server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://192.168.1.102:5432/assurePlusBD # <-- Exemple pour base distante
    username: kse
    password: "@Kse12345"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create # Supprime et recrée toutes les tables à chaque démarrage (ATTENTION : toutes les données seront perdues)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      INDENT_OUTPUT: true
  redis:
    host: localhost
    port: 6379

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Pour utiliser une base distante, adapte les variables ci-dessus ou utilise les variables d'environnement :
# SPRING_DATASOURCE_URL, SPRING_DATASOURCE_USERNAME, SPRING_DATASOURCE_PASSWORD 